### ISSUE TITLE
Show version information

### ISSUE THREAD

**Issue by paustint** [officert/mongotron#105]
About section should show version number so that I can know if updates have been made when comparing to the version in package.json on github.

I am imagining over time an auto-update feature would be implemented, so this would just be a first step prior to the full implementation.

**Comment by officert** [comment]
Added in https://github.com/officert/mongotron/commit/56ffcc7e8bfd1d866d5f11c4e937358cd1f40b81

<img width="1091" alt="screen shot 2016-02-08 at 2 53 18 pm" src="https://cloud.githubusercontent.com/assets/4620560/12897141/c19467c8-ce73-11e5-93e2-1a395da6211b.png">

I'm working on adding some kind of auto-update functionality, and eventually I'll add some release notes to this page about the current release you are using, etc...
