### ISSUE TITLE
is there no way to console.log() or print()?

### ISSUE THREAD

**Issue by LDubya** [officert/mongotron#116]
Sometimes I want to do some kind of operation and log the result. How do you log with mongotron?

**Comment by officert** [comment]
@LDubya I'm assuming you're talking about logging from the query editor. The current release, v1.0.0-alpha.3 doesn't support logging from the query editor, but I just added something quickly in master to allow this. Here's the commit if you're curious how to add additional support for things like this in the query editor:

https://github.com/officert/mongotron/commit/7df3f1705a926abcab7fb162ec0f45624759f0b3

If basically exposes a new object called ```console``` when evaluating your Javascript.

If you want to try it out just pull down and build the source. You'll be able to use console in the query editor.

**Comment by officert** [comment]
Not sure what the format should be quite yet, rights now it's just printing the whole ```arguments``` array.

**Comment by LDubya** [comment]
Alright, thanks for the quick response. I built it and console.log() doesn't throw any errors, but I'm not seeing any output. Where is the console.log() logging at, so that I can look at the output?

**Comment by LDubya** [comment]
@officert  Alright, thanks for the quick response. I built it and console.log() doesn't throw any errors, but I'm not seeing any output. Where is the console.log() logging at, so that I can look at the output?

**Comment by officert** [comment]
it will log right to the result view:

<img width="1077" alt="screen shot 2016-02-24 at 11 23 55 pm" src="https://cloud.githubusercontent.com/assets/4620560/13309776/c08645d6-db4d-11e5-9ef9-d363dfbc6cc9.png">
