### ISSUE TITLE
Error opening created database

### ISSUE THREAD

**Issue by BitsOnCoffee** [officert/mongotron#125]
When I create a new database, trying to open it I get:

    Error: error connecting to database at C:\Program Files\Mongotron-win32-x64\resources\app.asar\node_modules\lib\entities\database.js:74:29 at tryCatcher (C:\Program Files\Mongotron-win32-x64\resources\app.asar\node_modules\bluebird\js\release\util.js:11:23) at Promise._settlePromiseFromHandler (C:\Program Files\Mongotron-win32-x64\resources\app.asar\node_modules\bluebird\js\release\promise.js:489:31) at Promise._settlePromise (C:\Program Files\Mongotron-win32-x64\resources\app.asar\node_modules\bluebird\js\release\promise.js:546:18) at Promise._settlePromise0 (C:\Program Files\Mongotron-win32-x64\resources\app.asar\node_modules\bluebird\js\release\promise.js:591:10) at Promise._settlePromises (C:\Program Files\Mongotron-win32-x64\resources\app.asar\node_modules\bluebird\js\release\promise.js:674:18) at Async._drainQueue (C:\Program Files\Mongotron-win32-x64\resources\app.asar\node_modules\bluebird\js\release\async.js:129:16) at Async._drainQueues (C:\Program Files\Mongotron-win32-x64\resources\app.asar\node_modules\bluebird\js\release\async.js:139:10) at MutationObserver.Async.drainQueues (C:\Program Files\Mongotron-win32-x64\resources\app.asar\node_modules\bluebird\js\release\async.js:16:14) at process._tickCallback (node.js:392:9)

Also when I close Mongotron and reopen it again, database is missing.

_Edit: by mongo shell the database was created and filled successfuly._

**Comment by purexo** [comment]
Same problem here.
Mongotron did not create database. Must creating them in mongo shell.
