### ISSUE TITLE
Executable

### ISSUE THREAD

**Issue by kbariotis** [officert/mongotron#13]
Why not creating an executable so people can try it out more easily?

**Comment by officert** [comment]
Download an alpha release here:

https://github.com/officert/mongotron/releases

**Comment by kbariotis** [comment]
Ah oc! Thank you. Great job.

**Comment by officert** [comment]
No problem, would love to hear any feedback you have. Also, I just found a bug when creating a connection to a remove Mongo DB, so if you need that functionality let me know and I will create another pre-release with the bug. Otherwise connecting to a local db works fine.
