### ISSUE TITLE
Save connection without Database name and port

### ISSUE THREAD

**Issue by se** [officert/mongotron#136]
Hi, I am trying to save new connection without database name. It is saying optional but there is no way to pass them empty.

<img width="610" alt="screen shot 2016-05-17 at 12 09 41" src="https://cloud.githubusercontent.com/assets/491844/15317002/49a88624-1c28-11e6-86ea-e8d2df535b29.png">

**Comment by officert** [comment]
Hi, database name is only optional if you are connecting to local host. When connecting to a remote server connections are per database, so you'll need to enter the name.

**Comment by se** [comment]
Thank you for your explanation, But is there any way to develop it? I forked the project I will try to do that If there is no plan for that?

**Comment by officert** [comment]
The reason for this is that Mongotron uses the the node mongo db driver :

http://mongodb.github.io/node-mongodb-native/2.1/api/

which does not allow connecting to a remote database without a database name. So there is no plan to develop this as it does not seem possible using the driver. You are welcome to look into the issue some more if you'd like.
