### ISSUE TITLE
Remember view preference

### ISSUE THREAD

**Issue by iamtekeste** [officert/mongotron#140]
I really like working with the `table view` instead of the `key value` view. Right now mongotron does not remember my preference. For example If I select one collection and then change the view to `table view`, and then later go to another collection it is displays it in the `key value` view instead of `table view `view . 
I hope I have described my problem clearly. 
And also If you are busy maybe you can point me in the right direction and I will give it a try!

Thank you for the awesome app!

**Comment by officert** [comment]
Fixed in version [1.0.0-alpha.5](https://github.com/officert/mongotron/releases/tag/1.0.0-alpha.5)
