### ISSUE TITLE
Switching between collections should not keep opening new tabs

### ISSUE THREAD

**Issue by zusamann** [officert/mongotron#144]
Right now every time we open a collection a new tab opens, even if that collection has already been opened. 

I understand that tabs are meant to be the primary way of navigation, but many a times I find myself trying to navigate with the tree, because the tab title is always the query and never simply the name of the collection (which is one more thing I'd suggest to implement).

Instead a better UX in my view is when you click on a collection via tree, if it's tab is already opened, the view should simply be switched to that, instead of opening an entirely new tab

**Comment by officert** [comment]
Thank you for your suggestion, however we do this intentionally. Clicking on a collection name from the sidebar always launches a new `find()` query. It is not meant to be the primary navigation to your current queries, but a way to create new queries.
