### ISSUE TITLE
Error when calling db.collection.distinct

### ISSUE THREAD

**Issue by Phrozyn** [officert/mongotron#145]
db.collection.distinct('category')

Error : db.alerts.distinct is not a function TypeError: db.collection.distinct is not a function at evalmachine.:1:11 at ContextifyScript.Script.runInNewContext (vm.js:18:15) at /Users/username/Downloads/Mongotron-darwin-x64/Mongotron.app/Contents/Resources/app.asar/node_modules/lib/modules/expression/index.js:170:23 at Promise._execute (/Users/username/Downloads/Mongotron-darwin-x64/Mongotron.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/debuggability.js:159:9) at Promise._resolveFromExecutor (/Users/username/Downloads/Mongotron-darwin-x64/Mongotron.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:460:18) at new Promise (/Users/username/Downloads/Mongotron-darwin-x64/Mongotron.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:76:14) at _eval (/Users/username/Downloads/Mongotron-darwin-x64/Mongotron.app/Contents/Resources/app.asar/node_modules/lib/modules/expression/index.js:140:10) at /Users/username/Downloads/Mongotron-darwin-x64/Mongotron.app/Contents/Resources/app.asar/node_modules/lib/modules/expression/index.js:39:9 at Promise._execute (/Users/username/Downloads/Mongotron-darwin-x64/Mongotron.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/debuggability.js:159:9) at Promise._resolveFromExecutor (/Users/username/Downloads/Mongotron-darwin-x64/Mongotron.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:460:18)

However, if I log into the mongo shell and execute the same query, I get the list of categories.
MongoDB shell version: 2.4.8

(NOTE: collection name and username redacted and replaced with the term "collection" and term "username")

**Comment by Phrozyn** [comment]
I forgot to mention the version of Mongotron I am using is 1.0.0-alpha4

**Comment by officert** [comment]
Fixed in [1.0.0-alpha.5](https://github.com/officert/mongotron/releases/tag/1.0.0-alpha.5)
