### ISSUE TITLE
Authentication Fails

### ISSUE THREAD

**Issue by jhernandezb** [officert/mongotron#147]
Authentication fails  with passwords containing special characters like %,$ ... etc.

**Comment by PStoner3** [comment]
I may be doing something incorrectly, but I've tested this using a password containing =, %, and $. I am able to authenticate and log into my local instance just fine.

Are you able to provide any additional detail?

**Comment by jhernandezme** [comment]
Passwords I've tried is with ~%*_ , using SCRAM-SHA-1 authenticantion.
A solution that I've found is to use `encodeURIComponent` and `uri_decode_auth` when doing a new connection which is supported by the driver. [See here](https://mongodb.github.io/node-mongodb-native/api-generated/mongoclient.html#connect) 
```
newDb.auth.username = encodeURIComponent(options.auth.username);
newDb.auth.password = encodeURIComponent(options.auth.password);
client.connect(this.connectionString, {uri_decode_auth: true}, (err, database) => {});
```

**Comment by PStoner3** [comment]
Have you opened a PR for your solution? If not do you mind if I do? I will credit you with the fix.

**Comment by jhernandezme** [comment]
You are welcome! The only thing is that this change wont for previously saved passwords. must re-validate this.
