### ISSUE TITLE
Support chainable methods of a query

### ISSUE THREAD

**Issue by officert** [officert/mongotron#28]
Add support for chainable methods off a query.

Chainable methods to support:

* limit
* skip

Ex.

```
db.Users.find({
    name : 'John Doe'
}).sort({
    name : -1
}).limit(22)
```

**Comment by loganhuskins** [comment]
I don't think that it is just .sort() that isn't working. Unless I am mistaken, no chained functions work. 

For example :

```
db.users.find({}).limit(15)
```

**Comment by officert** [comment]
@loganhuskins yea chaining functions isn't supported at all right now. I just created this issue to start because someone expressed interested in implementing it. I've added another issue for adding limit() support:

https://github.com/officert/mongotron/issues/53

If there are other functions people would like supported let's get some issues created for each of them, anyone interested to implement can pick them up.

**Comment by jojobyte** [comment]
Yeah, should be able to work on this hopefully in the next couple days. Got busy with work trying to get stuff done before the holidays. We can probably rename this one to chaining or something and cover all of the mongo options, not just sort & limit.

**Comment by officert** [comment]
@jojobyte assigning this one to you. I'll close the other task and combine with this one and you can tackle adding support for any chainable method calls here.

**Comment by AddoSolutions** [comment]
+!

**Comment by officert** [comment]
Support for this was added in https://github.com/officert/mongotron/commit/1ba25333a217ffc848c560f07e7281cbbd031aca
