### ISSUE TITLE
Key value accordions should close all before opening

### ISSUE THREAD

**Issue by officert** [officert/mongotron#29]
In the key-value view, clicking an accordion should close all other accordions before opening. Only 1 should allowed to be open at a time.

Here's the current behavior :

<img width="1087" alt="screen shot 2015-12-04 at 9 45 32 pm" src="https://cloud.githubusercontent.com/assets/4620560/11605542/94cdb914-9ad0-11e5-88a9-4127a2a950db.png">

**Comment by joshmadewell** [comment]
Would you be more open to the idea of having a "collapse" all button that the user could click?

I think it could be potentially desired that someone has more than one open?

**Comment by officert** [comment]
@joshmadewell yea I think that makes sense. I created a new issue for it https://github.com/officert/mongotron/issues/39
