### ISSUE TITLE
Add a close all button for key-value view

### ISSUE THREAD

**Issue by officert** [officert/mongotron#39]
Add a collapse all button that is enabled when you're in key-value view. Clicking it should collapse any open key-values.

Button could go here somewhere:
<img width="1104" alt="screen shot 2015-12-20 at 9 57 26 pm" src="https://cloud.githubusercontent.com/assets/4620560/11922423/bed0846c-a764-11e5-9c21-5584e5032685.png">

**Comment by travispett** [comment]
Submitted a pull request for this. Not sure if you would want another button to expand all (or to change collapse all to expand all only when collapsed). I am not sure how much of a performance impact there would be with larger collections.
