### ISSUE TITLE
Tabs title text overflows

### ISSUE THREAD

**Issue by kinduff** [officert/mongotron#50]
**Release:** v1.0.0-alpha.2
**OS:** OS X v10.10.5

With multiple tabs opened the title text overflows, same thing happens when you resize the application window (no constraints). The Settings tab is a special case since it has an icon before the text.

![captura de pantalla 2015-12-23 a las 3 22 56 p m](https://cloud.githubusercontent.com/assets/1270156/11985353/8fa3761e-a989-11e5-8100-9eb1ce24fe70.png)

**Comment by officert** [comment]
:+1: thanks @kinduff
