### ISSUE TITLE
Support limit off the current query in a query tab

### ISSUE THREAD

**Issue by officert** [officert/mongotron#53]
Add support for limit right in the query editor.

Ex.

```
db.Users.find({
    name : 'John Doe'
}).limit(4)
```

**Comment by steezeburger** [comment]
Since find and the other methods are wrapping mongo calls, would we need to make these methods chainable, then add a sort(), limit(), etc?

**Comment by officert** [comment]
@steezeburger We just need to implement the parsing of the .limit() and other chainable methods in the query editor. Like you said we are just wrapping the node-mongodb methods, so it's just a matter of parsing a query to extract the limit, skip, etc...

If you look at the Collection class, where we are wrapping the methods, it's just a matter of passing down the skip and limit values as options.

The work to implement this would happen here

https://github.com/officert/mongotron/blob/master/src/lib/modules/query/parser.js

You'll see a bunch of regexes that are used to parse a query from the Codemirror editor, to extract the method name, the query, the options, etc... So we just need some regexes that can extract .limit().

**Comment by officert** [comment]
@steezeburger  I am closing this task because we have another task for supporting any chainable methods of queries:

https://github.com/officert/mongotron/issues/28
