### ISSUE TITLE
Use default theme, can not see command word

### ISSUE THREAD

**Issue by SimonSun1988** [officert/mongotron#55]
Like this

<a href="http://imgur.com/nSZRQI4"><img src="http://i.imgur.com/nSZRQI4.png" title="source: imgur.com" /></a>

**Comment by officert** [comment]
Yes this is a known-issue when using the default theme. I just haven't spent much time working on the default theme. If someone is interested in working on this bug take a look here:

https://github.com/officert/mongotron/tree/master/src/ui/less/themes

These are the less file for the themes that are currently available. The Atom theme is the one I've been using and is the most polished of the three.

To fix this bug we just need to tweak some of the Less variables for the query editor, you can find them here:

https://github.com/officert/mongotron/blob/master/src/ui/less/themes/atom-theme.less

look for these variables:

```
  //query
  @theme-query-editor-color: #c5c8c6;
  @theme-query-editor-bg: #c5c8c6;
  @theme-query-editor-border-color: lighten(@theme-bg, 10%);
  @theme-query-editor-input-bg: @theme-bg; //query edit skip + take input bg
  @theme-query-editor-string-color: #b5bd68;
  @theme-query-editor-boolean-color: #de935f;
  @theme-query-editor-key-color: #de935f;
  @theme-query-editor-keyword-color: #de935f;
  @theme-query-editor-variable-color: #f0c674;
```
