### ISSUE TITLE
Error Connecting .. see screenshot

### ISSUE THREAD

**Issue by kevbook** [officert/mongotron#63]
* Db is a remote DB
* Oplog not allowed on user
* Using the osx compiled version of the app

Not sure what else info could I provide. 

![image](https://cloud.githubusercontent.com/assets/926720/12012616/4a1d3e0a-accb-11e5-8915-971efecaec89.png)

**Comment by officert** [comment]
Could you try opening up the dev console and check and see if there are any errors?

You can open the dev console with cmd-option-i 
or go to the View menu > Toggle Developer Tools

**Comment by kevbook** [comment]
![image](https://cloud.githubusercontent.com/assets/926720/12013818/2c2b0acc-aced-11e5-89ab-284ce405f1ec.png)

**Comment by kevbook** [comment]
My me privately, I can share the creds to a sample remote DB you can connect and try it out.
Skype: ksakhuj

**Comment by officert** [comment]
Only thing I've found for this so far is this:

https://github.com/mongodb/js-bson/issues/152

I'll hop on Skype today and try and get those credentials from you so I can investigate some more.

**Comment by officert** [comment]
Alright so I am able to reproduce this on one of my databases. I now have 2 remote databases, each with authentication. 1 of them works fine, the other I get this error 'database.copy is not a function'.

It's definitely this same issue that is reported here https://github.com/mongodb/js-bson/issues/152.

The problem happens when trying to authenticate against the database. In my case the 1rst database is working and is using ```mongocr``` for an authentication provider, which is working. The 2nd database is using ```scram-sha-1``` which is not working.

**Comment by officert** [comment]
Based on mongodb/js-bson#152 this is happening because when running Node inside of Electron the window object is set to the browser window.

**Comment by officert** [comment]
@kevbook I was able to fix this in this commit:

https://github.com/officert/mongotron/commit/4988cff2cba82d090ed4d678f1bbc73c9563b540

I forked the node bson library and put in a fix, I'm now able to connect the the database I was having problems with. 

Do you mind checking and seeing if this clears things up for you? If you don't have all the development stuff setup I can create a new release for you to try out.

**Comment by joshmadewell** [comment]
I had this same issue with my database at work. I just tested and the issue is now resolved with your commit.

**Comment by kevbook** [comment]
It works now!!

**Comment by officert** [comment]
awesome yea so it's definitely an issue with mongo ~2.6 to mongo 3, where they changed the authentication mechanism. The library that the driver uses https://github.com/mongodb/js-bson doesn't play nice with Electron. In Electron the global window object is defined and set to the browser window, which messes up js-bson.
