### ISSUE TITLE
Click remove button but not reload

### ISSUE THREAD

**Issue by opjlmi** [officert/mongotron#66]
I thought it still not remove the connection
so I clicked again, and it showed the error.

and the reason why is
when I click the remove button, it removed the connection.
But the screen still not reload (or return to connections list)

<img width="1026" alt="2015-12-29 4 04 34" src="https://cloud.githubusercontent.com/assets/6351593/12031363/f55fe1f2-ae45-11e5-9ae6-c197455b2c6e.png">

**Comment by officert** [comment]
Fixed in https://github.com/officert/mongotron/commit/f242cd3b04798cc16fe2d43e0591eeb1fd6561ef
