### ISSUE TITLE
gulp release issue

### ISSUE THREAD

**Issue by kevinlincg** [officert/mongotron#82]
When build release mongotron, it has Error missing package.json like below.
 Error: Error: ENOENT: no such file or directory, stat 'C:\mongotron\node_modules\package.json'

**Comment by officert** [comment]
@kevinlincg can you pull the latest code and try again? I just pushed a commit that I think should fix the issue your getting.

**Comment by kevinlincg** [comment]
@officert this pull isn't fix the issue , I think it may be gul-symlink's bug on windows10
