### ISSUE TITLE
Google Chrome blocking download

### ISSUE THREAD

**Issue by brentcrammond** [officert/mongotron#83]
Currently Google Chrome is detecting the Darwin download as malicious.

**Comment by mikaoelitiana** [comment]
I am having the same issue downloading the osx version.

**Comment by mikaoelitiana** [comment]
I am having the same issue while downloading the osx version.

**Comment by officert** [comment]
this is a known issue, closing this because it's a duplicate.

https://github.com/officert/mongotron/issues/64

**Comment by officert** [comment]
For now you will need to clone the git repo, then you can run 

```
gulp release-osx
```

this will create a ```release``` directory containing the executable.
