### ISSUE TITLE
Using db['collection-name'].find({}) doesn't work.

### ISSUE THREAD

**Issue by Crenshinibon** [officert/mongotron#87]
The native Mongo CLI allows for this notation in case the collection name contains otherwise 'illegal' characters (for the JS dot notation, for accessing attributes). Would be great if you could adjust mongotron to allow this query.

**Comment by officert** [comment]
@Crenshinibon this will be in the next release of Mongotron. If you are running from the source you can use the https://github.com/officert/mongotron/tree/escodegen branch which currently supports this notation, as well as chaining functions.

**Comment by Crenshinibon** [comment]
Great. Thanks. I will run it from the source branch, then. Are those rather
stable? A data loss would be inconvenient.

Tim Officer <notifications@github.com> schrieb am Mi., 27. Jan. 2016 um
17:51 Uhr:

**Comment by officert** [comment]
Yes the [escodegen branch](https://github.com/officert/mongotron/tree/escodegen) is fairly stable. Some of the functionality like export to csv and possibly editing documents inline are broken, but querying data is working fine. Mongotron does support methods like deleteOne and deleteMany which will obviously result in data loss. All of the methods in the query class are exposed in the Mongotron editor https://github.com/officert/mongotron/blob/escodegen/src/lib/entities/collection.js.

* insertOne
* find
* count
* deleteMany
* deleteById
* deleteOne
* aggregate
* updateMany
* updateOne
* updateById
* drop
