### ISSUE TITLE
Can't connect to localhost IP 

### ISSUE THREAD

**Issue by imaustink** [officert/mongotron#91]
OSX: 10.10.5.
Mongotron: v1.0.0-alpha.2.
Works fine with ```localhost``` but not ```127.0.0.1```.

**Comment by officert** [comment]
@imaustink this bug is fixed in the master branch https://github.com/officert/mongotron/commit/969695f867ea9347e2d4d61b95505ab2de10c891#diff-f8981c72ecf05267b541ecfbdf366720
